name: Genera EPG
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Installa Bun
        uses: oven-sh/setup-bun@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Genera EPG
        shell: bash
        working-directory: ./
        run: |
          bun install
          bun generate.mjs

      - name: Carica per GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    name: Deploy
    needs: generate

    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Scarica & deploya artifact
        id: deployment
        uses: actions/deploy-pages@v4